Price package key disclaimer
vippsas/vipps-partner-api pull request #27
Opened 2022-07-06 13:54 UTC by ananthb86

2022-07-06 14:14 UTC, Haldormyre commented on vipps-partner-api.md
> +for the partner to send in correct information for `pricePakcageKey` in the request.
Typo in `pricePackageKey`

2022-07-06 14:17 UTC, cloveras commented on docs/swagger.yaml
> +          description: One of the price package that is registered for the partner in Vipps system. Please note, it is not the PriceId (3 digit) but the name such as standard, price1, etc that is app
Add quotes: "standard", "price1"

2022-07-06 14:18 UTC, cloveras requested changes
So close!

2022-07-06 14:19 UTC, cloveras commented on docs/swagger.yaml
> +          description: One of the price package that is registered for the partner in Vipps system. Please note, it is not the PriceId (3 digit) but the name such as standard, price1, etc that is app
```suggestion
          description: One of the price package that is registered for the partner in Vipps system. Please note, it is not the PriceId (3 digit) but the name such as "standard", "price1", etc that is applicable to the partner.
```

2022-07-06 14:20 UTC, cloveras commented on vipps-partner-api.md
> +for the partner to send in correct information for `pricePakcageKey` in the request.
```suggestion
for the partner to send in correct information for `pricePackageKey` in the request. 
```

2022-08-15 08:51 UTC, cloveras approved these changes
LGTM

2022-08-16 10:47 UTC, cloveras approved these changes

2022-08-16 10:49 UTC, cloveras approved these changes

2022-08-16 10:49 UTC, merged